challenge:
  outputs:
    dev:
      type: postgres
      host: datastreet_pg
      user: postgres
      pass: postgres
      port: 5432
      dbname: datastreet
      schema: raw
      threads: 4
  target: dev
